export const style = `

@import url('https://fonts.googleapis.com/css2?family=Oswald&display=swap');

@import url('https://fonts.googleapis.com/css2?family=Grechen+Fuemen&display=swap');

#container {
  display: flex;
  align-items: center;
  margin-bottom: 20px;
}

.none{
  display:flex;
  width:100%;
  height:100%;
  position: absolute;
  left: 745px;
}

.param{
    margin-bottom:3px;
}

#showControlsDiv {
  font-family: Georgia, serif;
  color: white;
  text-align:center;
  margin-left:20px;
}

#controlPanel {
  font-family: Georgia, serif;
  margin-left:30px;
  padding: 10px;
  background-color:#dedede;
  width:500px;
  border-radius: 8px;
  border: #5e5c5a solid 2px;
}

#panelTitle{
  display:flex;
  justify-content: center;
  font-weight: 700;
  margin-bottom:5px;
}


#logoBg{
  display:flex;
  width:100%;
  height:100%;
  position:absolute;
}

#logoText{
  display:flex;
}

#logo {
  margin-left:30px;
  font-size:40px;
  color:yellow;
  display:inline-block;
  font-family: 'Grechen Fuemen', cursive;
  text-shadow: 0 1px 0 #ccc,
                0 2px 0 #c9c9c9,
                0 3px 0 #bbb,
                0 4px 0 #b9b9b9,
                0 5px 0 #aaa,
                0 6px 1px rgba(0,0,0,.1),
                0 0 5px rgba(0,0,0,.1),
                0 1px 3px rgba(0,0,0,.3),
                0 3px 5px rgba(0,0,0,.2),
                0 5px 10px rgba(0,0,0,.25),
                0 10px 10px rgba(0,0,0,.2),
                0 20px 20px rgba(0,0,0,.15);
}


.text-pop-up-tr {
	-webkit-animation: text-pop-up-tr 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: text-pop-up-tr 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-9-26 12:4:3
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-pop-up-tr
 * ----------------------------------------
 */
@-webkit-keyframes text-pop-up-tr {
  0% {
    -webkit-transform: translateY(0) translateX(0);
            transform: translateY(0) translateX(0);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
    text-shadow: none;
  }
  100% {
    -webkit-transform: translateY(-50px) translateX(50px);
            transform: translateY(-50px) translateX(50px);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
    text-shadow: 0 1px 0 #cccccc, 0 2px 0 #cccccc, 0 3px 0 #cccccc, 0 4px 0 #cccccc, 0 5px 0 #cccccc, 0 6px 0 #cccccc, 0 7px 0 #cccccc, 0 8px 0 #cccccc, 0 9px 0 #cccccc, 0 50px 30px rgba(0, 0, 0, 0.3);
  }
}
@keyframes text-pop-up-tr {
  0% {
    -webkit-transform: translateY(0) translateX(0);
            transform: translateY(0) translateX(0);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
    text-shadow: none;
  }
  100% {
    -webkit-transform: translateY(-50px) translateX(50px);
            transform: translateY(-50px) translateX(50px);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
    text-shadow: 0 1px 0 #cccccc, 0 2px 0 #cccccc, 0 3px 0 #cccccc, 0 4px 0 #cccccc, 0 5px 0 #cccccc, 0 6px 0 #cccccc, 0 7px 0 #cccccc, 0 8px 0 #cccccc, 0 9px 0 #cccccc, 0 50px 30px rgba(0, 0, 0, 0.3);
  }
}


.focus-in-expand {
	-webkit-animation: focus-in-expand 0.8s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: focus-in-expand 0.8s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-9-26 12:1:27
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation focus-in-expand
 * ----------------------------------------
 */
@-webkit-keyframes focus-in-expand {
  0% {
    letter-spacing: -0.5em;
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}
@keyframes focus-in-expand {
  0% {
    letter-spacing: -0.5em;
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}


.tracking-in-contract-bck {
	-webkit-animation: tracking-in-contract-bck 1s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
	        animation: tracking-in-contract-bck 1s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-9-26 11:38:39
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-contract-bck
 * ----------------------------------------
 */
@-webkit-keyframes tracking-in-contract-bck {
  0% {
    letter-spacing: 1em;
    -webkit-transform: translateZ(400px);
            transform: translateZ(400px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;
  }
}
@keyframes tracking-in-contract-bck {
  0% {
    letter-spacing: 1em;
    -webkit-transform: translateZ(400px);
            transform: translateZ(400px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;
  }
}


.wobble-ver-left {
	-webkit-animation: wobble-ver-left 0.8s infinite both;
	        animation: wobble-ver-left 0.8s infinite both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-9-26 11:9:27
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation wobble-ver-left
 * ----------------------------------------
 */
@-webkit-keyframes wobble-ver-left {
  0%,
  100% {
    -webkit-transform: translateY(0) rotate(0);
            transform: translateY(0) rotate(0);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
  }
  15% {
    -webkit-transform: translateY(-30px) rotate(-6deg);
            transform: translateY(-30px) rotate(-6deg);
  }
  30% {
    -webkit-transform: translateY(15px) rotate(6deg);
            transform: translateY(15px) rotate(6deg);
  }
  45% {
    -webkit-transform: translateY(-15px) rotate(-3.6deg);
            transform: translateY(-15px) rotate(-3.6deg);
  }
  60% {
    -webkit-transform: translateY(9px) rotate(2.4deg);
            transform: translateY(9px) rotate(2.4deg);
  }
  75% {
    -webkit-transform: translateY(-6px) rotate(-1.2deg);
            transform: translateY(-6px) rotate(-1.2deg);
  }
}
@keyframes wobble-ver-left {
  0%,
  100% {
    -webkit-transform: translateY(0) rotate(0);
            transform: translateY(0) rotate(0);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
  }
  15% {
    -webkit-transform: translateY(-30px) rotate(-6deg);
            transform: translateY(-30px) rotate(-6deg);
  }
  30% {
    -webkit-transform: translateY(15px) rotate(6deg);
            transform: translateY(15px) rotate(6deg);
  }
  45% {
    -webkit-transform: translateY(-15px) rotate(-3.6deg);
            transform: translateY(-15px) rotate(-3.6deg);
  }
  60% {
    -webkit-transform: translateY(9px) rotate(2.4deg);
            transform: translateY(9px) rotate(2.4deg);
  }
  75% {
    -webkit-transform: translateY(-6px) rotate(-1.2deg);
            transform: translateY(-6px) rotate(-1.2deg);
  }
}

  
.roll-in-left {
-webkit-animation: roll-in-left 0.6s ease-out both;
        animation: roll-in-left 0.6s ease-out both;
}

/* ----------------------------------------------
* Generated by Animista on 2021-9-25 15:33:39
* Licensed under FreeBSD License.
* See http://animista.net/license for more info. 
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */
 
 /**
  * ----------------------------------------
  * animation roll-in-left
  * ----------------------------------------
  */
 @-webkit-keyframes roll-in-left {
   0% {
     -webkit-transform: translateX(-800px) rotate(-540deg);
             transform: translateX(-800px) rotate(-540deg);
     opacity: 0;
   }
   100% {
     -webkit-transform: translateX(0) rotate(0deg);
             transform: translateX(0) rotate(0deg);
     opacity: 1;
   }
 }
 @keyframes roll-in-left {
   0% {
     -webkit-transform: translateX(-800px) rotate(-540deg);
             transform: translateX(-800px) rotate(-540deg);
     opacity: 0;
   }
   100% {
     -webkit-transform: translateX(0) rotate(0deg);
             transform: translateX(0) rotate(0deg);
     opacity: 1;
   }
 }
       
  
.jello-horizontal {
        animation: jello-horizontal 0.9s infinite both;
}

@keyframes jello-horizontal {
0% {
            transform: scale3d(1, 1, 1);
}
30% {
            transform: scale3d(1.25, 0.75, 1);
}
40% {
            transform: scale3d(0.75, 1.25, 1);
}
50% {
            transform: scale3d(1.15, 0.85, 1);
}
65% {
            transform: scale3d(0.95, 1.05, 1);
}
75% {
            transform: scale3d(1.05, 0.95, 1);
}
100% {
            transform: scale3d(1, 1, 1);
}
}

.heartbeat {
    animation: heartbeat 1.5s ease-in-out infinite both;
} 
/* ----------------------------------------------
* Generated by Animista on 2021-9-25 10:19:54
* Licensed under FreeBSD License.
* See http://animista.net/license for more info. 
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

 /**
  * ----------------------------------------
  * animation heartbeat
  * ----------------------------------------
  */
 @keyframes heartbeat {
   from {
             transform: scale(1);
             transform-origin: center center;
             animation-timing-function: ease-out;
   }
   10% {
             transform: scale(0.91);
             animation-timing-function: ease-in;
   }
   17% {
             transform: scale(0.98);
             animation-timing-function: ease-out;
   }
   33% {
             transform: scale(0.87);
             animation-timing-function: ease-in;
   }
   45% {
             transform: scale(1);
             animation-timing-function: ease-out;
   }
 }


 .flip-horizontal-bottom {
  -webkit-animation: flip-horizontal-bottom 1.5s cubic-bezier(0.455, 0.030, 0.515, 0.955) infinite both;
          animation: flip-horizontal-bottom 1.5s cubic-bezier(0.455, 0.030, 0.515, 0.955) infinite both;
}

/* ----------------------------------------------
* Generated by Animista on 2021-9-25 15:29:4
* Licensed under FreeBSD License.
* See http://animista.net/license for more info. 
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

/**
* ----------------------------------------
* animation flip-horizontal-bottom
* ----------------------------------------
*/
@-webkit-keyframes flip-horizontal-bottom {
0% {
-webkit-transform: rotateX(0);
        transform: rotateX(0);
}
100% {
-webkit-transform: rotateX(-180deg);
        transform: rotateX(-180deg);
}
}
@keyframes flip-horizontal-bottom {
0% {
-webkit-transform: rotateX(0);
        transform: rotateX(0);
}
100% {
-webkit-transform: rotateX(-180deg);
        transform: rotateX(-180deg);
}
}


 .rotate-diagonal-1 {
  -webkit-animation: rotate-diagonal-1 3s linear infinite both;
          animation: rotate-diagonal-1 3s linear infinite both;
}

/* ----------------------------------------------
* Generated by Animista on 2021-9-25 20:3:7
* Licensed under FreeBSD License.
* See http://animista.net/license for more info. 
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

/**
* ----------------------------------------
* animation rotate-diagonal-1
* ----------------------------------------
*/
@-webkit-keyframes rotate-diagonal-1 {
0% {
-webkit-transform: rotate3d(1, 1, 0, 0deg);
        transform: rotate3d(1, 1, 0, 0deg);
}
50% {
-webkit-transform: rotate3d(1, 1, 0, -180deg);
        transform: rotate3d(1, 1, 0, -180deg);
}
100% {
-webkit-transform: rotate3d(1, 1, 0, -360deg);
        transform: rotate3d(1, 1, 0, -360deg);
}
}
@keyframes rotate-diagonal-1 {
0% {
-webkit-transform: rotate3d(1, 1, 0, 0deg);
        transform: rotate3d(1, 1, 0, 0deg);
}
50% {
-webkit-transform: rotate3d(1, 1, 0, -180deg);
        transform: rotate3d(1, 1, 0, -180deg);
}
100% {
-webkit-transform: rotate3d(1, 1, 0, -360deg);
        transform: rotate3d(1, 1, 0, -360deg);
}
}

.rotate-center {
-webkit-animation: rotate-center 2s ease-in-out infinite both;
        animation: rotate-center 2s ease-in-out infinite both;
}

/* ----------------------------------------------
* Generated by Animista on 2021-9-25 20:10:48
* Licensed under FreeBSD License.
* See http://animista.net/license for more info. 
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

/**
* ----------------------------------------
* animation rotate-center
* ----------------------------------------
*/
@-webkit-keyframes rotate-center {
0% {
-webkit-transform: rotate(0);
        transform: rotate(0);
}
100% {
-webkit-transform: rotate(360deg);
        transform: rotate(360deg);
}
}
@keyframes rotate-center {
0% {
-webkit-transform: rotate(0);
        transform: rotate(0);
}
100% {
-webkit-transform: rotate(360deg);
        transform: rotate(360deg);
}
}


 
`;